### ISSUE TITLE
Composer autoloader

### ISSUE THREAD

**Issue by bashilbers** [iConneqt/PHP-REST-API-client#1]
Why do I need to adjust our autoload in order for this package to autoload?

Is there some sort of directory structure mapping problem? I have never seen composer packages that require such a change on the autoloader.

I would like to use your API client, but I can't if it requires to add a path to our autoloader..

**Comment by vanderlee** [comment]
My apologies. The example provided in the composer documentation at https://getcomposer.org/doc/04-schema.md#psr-4 was bad. It's fixed now and autoload uses the right location now after a `require` (or `update` if already installed ;)).

I've submitted a pull request at composer to get their documentation fixed (https://github.com/composer/composer/compare/master...vanderlee:patch-1)
