### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by bashilbers** [iConneqt/PHP-REST-API-client#2]
Would it be possible to create a 1.0.0 or 0.0.1 tag, so that our minimum-stability of "stable" can he adhered? (also feels a bit better than to fixate a specific commit hash on dev-master)

**Comment by vanderlee** [comment]
It's been at 1.0.1 for a few days now.
If you `composer require iconneqt/rest-api-client`, you will get the  most recent stable branch automatically (currently still 1.0.1).

Packagist (which is the default package manager for composer) also correctly lists 1.0.1; https://packagist.org/packages/iconneqt/rest-api-client

Perhaps there's a problem with your composer installation? Try doing a `composer self-update`.

**Comment by vanderlee** [comment]
Closing assuming resolved
